### ISSUE TITLE
but can it run in alpha36.1 

### ISSUE THREAD

**Issue by tgd-git** [vvvv/VL.GStreamer#2]
is this a kind of demo for gstreamer integration? it seems not to run in latest alpha. i followed the readme and tried the birds mp4 from the vvvv assets. renderer is black, no texture

**Comment by azeno** [comment]
Indeed the "download latest version of GStreamer" wasn't correct. I've updated the package to GStreamer 1.14.2 and clarified in readme. Should work now with latest alpha builds.
